from __future__ import annotations

from enum import StrEnum


class MetricStatus(StrEnum):
    COMPUTED = "COMPUTED"
    COMPARED = "COMPARED"
    NOT_COMPUTABLE = "NOT_COMPUTABLE"
    NOT_VERIFIED = "NOT_VERIFIED"
    INSUFFICIENT_SAMPLE = "INSUFFICIENT_SAMPLE"


class ComparisonAvailability(StrEnum):
    AVAILABLE = "AVAILABLE"
    BLOCKED = "BLOCKED"


class SupportedQuantile(StrEnum):
    P50 = "P50"
    P80 = "P80"
    P90 = "P90"


class CrossQuantileInputSource(StrEnum):
    S2_IMMUTABLE_BACKTEST_BINDING = "S2_IMMUTABLE_BACKTEST_BINDING"


class FrozenVersion(StrEnum):
    METRIC_INPUT_MASK_V1 = "v0.2-s3-metric-input-mask-v1"
    NAIVE_BASELINE_POLICY_V1 = "v0.2-s3-naive-baseline-policy-v1"
    SEASON_ANALOG_MAPPING_V1 = "v0.2-s3-season-analog-mapping-v1"


class ReasonCode(StrEnum):
    NONE = "NONE"
    NO_MAPE_ELIGIBLE_ROWS = "NO_MAPE_ELIGIBLE_ROWS"
    MAPE_DENOMINATOR_ZERO = "MAPE_DENOMINATOR_ZERO"
    WAPE_DENOMINATOR_ZERO = "WAPE_DENOMINATOR_ZERO"
    RELATIVE_BIAS_DENOMINATOR_ZERO = "RELATIVE_BIAS_DENOMINATOR_ZERO"
    NO_COMPLETE_7DAY_WINDOW = "NO_COMPLETE_7DAY_WINDOW"
    QUANTILE_SEMANTICS_NOT_VERIFIED = "QUANTILE_SEMANTICS_NOT_VERIFIED"
    BELOW_MINIMUM = "BELOW_MINIMUM"
    BASELINE_QUANTILE_DISTRIBUTION_NOT_DEFINED = "BASELINE_QUANTILE_DISTRIBUTION_NOT_DEFINED"
    COMPLETE_DAILY_ROW_SET_NOT_AVAILABLE_FROM_S2_BINDING = (
        "COMPLETE_DAILY_ROW_SET_NOT_AVAILABLE_FROM_S2_BINDING"
    )
    SIGNED_DIRECTION_ONLY = "SIGNED_DIRECTION_ONLY"
    PREDICTION_INTERVAL_LOWER_BOUND_UNAVAILABLE = "PREDICTION_INTERVAL_LOWER_BOUND_UNAVAILABLE"
    NO_PRIOR_SEASON_ANALOG_DAY = "NO_PRIOR_SEASON_ANALOG_DAY"
    NO_PRIOR_SEASON_ANALOG_ACTUAL = "NO_PRIOR_SEASON_ANALOG_ACTUAL"
    BASELINE_SOURCE_NOT_VISIBLE_AT_CURRENT_FORECAST_CUTOFF = (
        "BASELINE_SOURCE_NOT_VISIBLE_AT_CURRENT_FORECAST_CUTOFF"
    )
    NO_S2_BINDING_ROWS = "NO_S2_BINDING_ROWS"
