"""Frozen V0.3 Farm-total baseline policy constants."""

from __future__ import annotations

FARM_TOTAL_AREA_POLICY_VERSION = "v0-3-farm-total-area-proxy-policy-v1"
FARM_TOTAL_MAPPING_POLICY_VERSION = "v0-3-baseline-farm-group-mapping-r2-high-v1"
FARM_TOTAL_MAPPING_SCHEMA_VERSION = "v0-3-farm-total-group-mapping-package-v1"
FARM_TOTAL_AREA_AUTHORITY_SCHEMA_VERSION = "v0-3-farm-total-area-authority-package-v1"
FARM_TOTAL_DATASET_SCHEMA_VERSION = "v0-3-farm-total-dataset-v1"

FARM_TOTAL_TARGET_SEASON = "2025~2026"
FARM_TOTAL_PRIOR_AREA_SOURCE_SEASON = "2024~2025"

V0_3_BASELINE_TARGET = "FARM_TOTAL_HARVEST_QUANTITY"
V0_3_BASELINE_ENTITY = "BASELINE_FARM_GROUP"

AREA_AUTHORITY_CLASS_PREVIOUS_SEASON_PROXY = "PREVIOUS_SEASON_PROXY"
AREA_AUTHORITY_CLASS_CURRENT_SEASON_CONFIRMED = "CURRENT_SEASON_CONFIRMED"
AREA_AUTHORITY_CLASS_NOT_ELIGIBLE = "NOT_ELIGIBLE"

EXCLUSION_REASON_TEMPORAL_CONFLICT = "CURRENT_VS_PREVIOUS_CONFLICT"

# Owner-authorized mandatory exclusions from R3 temporal reconciliation.
CONFLICT_EXCLUDED_BASELINE_FARM_GROUPS: frozenset[str] = frozenset({"双龙营", "新哨", "盘龙"})

# Reviewed R3 population invariants (fail-closed verification targets).
REVIEWED_ELIGIBLE_PROXY_GROUP_COUNT = 31
REVIEWED_ELIGIBLE_PROXY_AREA_MU = "21719.09138059892957"
REVIEWED_ELIGIBLE_PROXY_HISTORICAL_HARVEST_KG = "20712999.546"
REVIEWED_HIGH_CONFIDENCE_GROUP_COUNT = 34
