from __future__ import annotations

from enum import StrEnum
from typing import Any


class ActualHarvestApiErrorCode(StrEnum):
    ACTUAL_HARVEST_AUTHORIZATION_UNAVAILABLE = "ACTUAL_HARVEST_AUTHORIZATION_UNAVAILABLE"
    ACTUAL_HARVEST_SCOPE_FORBIDDEN = "ACTUAL_HARVEST_SCOPE_FORBIDDEN"
    ACTUAL_HARVEST_ACTOR_MISMATCH = "ACTUAL_HARVEST_ACTOR_MISMATCH"
    IMPORT_BATCH_NOT_FOUND = "IMPORT_BATCH_NOT_FOUND"
    IMPORT_BATCH_NOT_UPLOADING = "IMPORT_BATCH_NOT_UPLOADING"
    IMPORT_BATCH_CANCELLED = "IMPORT_BATCH_CANCELLED"
    IMPORT_BATCH_CANNOT_CANCEL = "IMPORT_BATCH_CANNOT_CANCEL"
    IDEMPOTENCY_KEY_CONFLICT = "IDEMPOTENCY_KEY_CONFLICT"
    EXTERNAL_BATCH_ID_CONFLICT = "EXTERNAL_BATCH_ID_CONFLICT"
    REVISION_IDENTITY_CONFLICT = "REVISION_IDENTITY_CONFLICT"
    REVISION_NUMBER_CONFLICT = "REVISION_NUMBER_CONFLICT"
    BATCH_ALREADY_SEALED = "BATCH_ALREADY_SEALED"
    BATCH_NOT_SEALED = "BATCH_NOT_SEALED"
    BATCH_RECORD_COUNT_MISMATCH = "BATCH_RECORD_COUNT_MISMATCH"
    BATCH_MUTATION_AFTER_SEAL = "BATCH_MUTATION_AFTER_SEAL"
    BATCH_SEAL_HASH_CONFLICT = "BATCH_SEAL_HASH_CONFLICT"
    BATCH_SEAL_CHANGED = "BATCH_SEAL_CHANGED"
    SERVER_GENERATED_FIELD_SUPPLIED = "SERVER_GENERATED_FIELD_SUPPLIED"
    API_REQUEST_BODY_TOO_LARGE = "API_REQUEST_BODY_TOO_LARGE"
    API_RECORD_PAGE_TOO_LARGE = "API_RECORD_PAGE_TOO_LARGE"
    API_PAGE_SIZE_INVALID = "API_PAGE_SIZE_INVALID"
    API_CONTENT_TYPE_UNSUPPORTED = "API_CONTENT_TYPE_UNSUPPORTED"
    API_REQUEST_INVALID = "API_REQUEST_INVALID"
    API_INTEGRITY_ERROR = "API_INTEGRITY_ERROR"


class ActualHarvestApiError(RuntimeError):
    """Safe, stable error crossing the actual-harvest HTTP boundary."""

    def __init__(
        self,
        code: ActualHarvestApiErrorCode,
        message: str,
        *,
        status_code: int,
        details: dict[str, Any] | None = None,
    ) -> None:
        super().__init__(message)
        self.code = code
        self.message = message
        self.status_code = status_code
        self.details = details or {}


__all__ = ["ActualHarvestApiError", "ActualHarvestApiErrorCode"]
