from __future__ import annotations

from enum import StrEnum


class ActualHarvestImportChannel(StrEnum):
    API = "api"
    CSV = "csv"
    XLSX = "xlsx"


class ActualHarvestPhysicalEvent(StrEnum):
    FARM_PICK = "FARM_PICK"


class ActualHarvestQuantityBasis(StrEnum):
    OBSERVED_WEIGHT = "OBSERVED_WEIGHT"


class ActualHarvestQuantityUnit(StrEnum):
    KG = "KG"


class ActualHarvestMissingRecordSemantics(StrEnum):
    UNKNOWN_NOT_ZERO = "UNKNOWN_NOT_ZERO"


class ActualHarvestRecordStatus(StrEnum):
    ACTIVE = "ACTIVE"
    CORRECTED = "CORRECTED"
    VOID = "VOID"
    FINALIZED = "FINALIZED"


class SourceRecordedAtAuthorityStatus(StrEnum):
    TRUSTED_SOURCE_TIMESTAMP = "TRUSTED_SOURCE_TIMESTAMP"
    USER_ASSERTED_UNVERIFIED = "USER_ASSERTED_UNVERIFIED"
    MISSING = "MISSING"
    CONFLICTING = "CONFLICTING"


class ActualHarvestImportBatchStatus(StrEnum):
    RECEIVED = "RECEIVED"
    UPLOADING = "UPLOADING"
    SEALED = "SEALED"
    PARSING = "PARSING"
    PARSE_FAILED = "PARSE_FAILED"
    VALIDATING = "VALIDATING"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    VALIDATED = "VALIDATED"
    COMMITTING = "COMMITTING"
    COMMITTED = "COMMITTED"
    COMMIT_FAILED = "COMMIT_FAILED"
    CANCELLED = "CANCELLED"


class ActualHarvestBatchSealStatus(StrEnum):
    UNSEALED = "UNSEALED"
    SEALED = "SEALED"


class ActualHarvestValidationSeverity(StrEnum):
    ERROR = "ERROR"
    WARNING = "WARNING"


class ActualHarvestValidationErrorCode(StrEnum):
    CSV_ENCODING_INVALID = "CSV_ENCODING_INVALID"
    CSV_STRUCTURE_INVALID = "CSV_STRUCTURE_INVALID"
    CSV_LIMIT_EXCEEDED = "CSV_LIMIT_EXCEEDED"
    CSV_EMPTY_ROW_IGNORED = "CSV_EMPTY_ROW_IGNORED"
    CANONICAL_HEADER_DUPLICATE = "CANONICAL_HEADER_DUPLICATE"
    CANONICAL_HEADER_COLLISION = "CANONICAL_HEADER_COLLISION"
    XLSX_CANONICAL_SHEET_MISSING = "XLSX_CANONICAL_SHEET_MISSING"
    XLSX_CANONICAL_SHEET_DUPLICATE = "XLSX_CANONICAL_SHEET_DUPLICATE"
    XLSX_EXTRA_SHEET_FORBIDDEN = "XLSX_EXTRA_SHEET_FORBIDDEN"
    XLSX_FORMULA_CELL_FORBIDDEN = "XLSX_FORMULA_CELL_FORBIDDEN"
    XLSX_MERGED_CELL_FORBIDDEN = "XLSX_MERGED_CELL_FORBIDDEN"
    XLSX_HIDDEN_ROW_FORBIDDEN = "XLSX_HIDDEN_ROW_FORBIDDEN"
    XLSX_HIDDEN_COLUMN_FORBIDDEN = "XLSX_HIDDEN_COLUMN_FORBIDDEN"
    XLSX_EXECUTABLE_CONTENT_FORBIDDEN = "XLSX_EXECUTABLE_CONTENT_FORBIDDEN"
    XLSX_EXTERNAL_LINK_FORBIDDEN = "XLSX_EXTERNAL_LINK_FORBIDDEN"
    XLSX_ARCHIVE_INVALID = "XLSX_ARCHIVE_INVALID"
    XLSX_LIMIT_EXCEEDED = "XLSX_LIMIT_EXCEEDED"
    SERVER_GENERATED_FIELD_SUPPLIED = "SERVER_GENERATED_FIELD_SUPPLIED"
    TEMPLATE_POLICY_INCOMPATIBLE = "TEMPLATE_POLICY_INCOMPATIBLE"
    REQUIRED_FIELD_MISSING = "REQUIRED_FIELD_MISSING"
    UNKNOWN_FIELD = "UNKNOWN_FIELD"
    INVALID_DATE = "INVALID_DATE"
    INVALID_DATETIME = "INVALID_DATETIME"
    INVALID_TIMEZONE = "INVALID_TIMEZONE"
    INVALID_DECIMAL = "INVALID_DECIMAL"
    NEGATIVE_QUANTITY = "NEGATIVE_QUANTITY"
    IDENTITY_MAPPING_NOT_FOUND = "IDENTITY_MAPPING_NOT_FOUND"
    IDENTITY_MAPPING_AMBIGUOUS = "IDENTITY_MAPPING_AMBIGUOUS"
    DUPLICATE_RECORD = "DUPLICATE_RECORD"
    IDEMPOTENCY_KEY_CONFLICT = "IDEMPOTENCY_KEY_CONFLICT"
    REVISION_NUMBER_CONFLICT = "REVISION_NUMBER_CONFLICT"
    REVISION_IDENTITY_CONFLICT = "REVISION_IDENTITY_CONFLICT"
    REVISION_PREDECESSOR_MISSING = "REVISION_PREDECESSOR_MISSING"
    REVISION_MULTIPLE_SUCCESSORS = "REVISION_MULTIPLE_SUCCESSORS"
    REVISION_LINEAGE_CYCLE = "REVISION_LINEAGE_CYCLE"
    REVISION_LOGICAL_RECORD_MISMATCH = "REVISION_LOGICAL_RECORD_MISMATCH"
    MULTIPLE_TERMINAL_REVISIONS = "MULTIPLE_TERMINAL_REVISIONS"
    INVALID_RECORD_STATUS = "INVALID_RECORD_STATUS"
    SOURCE_SEMANTICS_ATTESTATION_MISSING = "SOURCE_SEMANTICS_ATTESTATION_MISSING"
    SOURCE_SEMANTICS_NOT_FARM_PICK = "SOURCE_SEMANTICS_NOT_FARM_PICK"
    BATCH_NOT_VALIDATED = "BATCH_NOT_VALIDATED"
    BATCH_ALREADY_COMMITTED = "BATCH_ALREADY_COMMITTED"
    CANONICAL_HASH_MISMATCH = "CANONICAL_HASH_MISMATCH"
    BATCH_NOT_SEALED = "BATCH_NOT_SEALED"
    BATCH_ALREADY_SEALED = "BATCH_ALREADY_SEALED"
    BATCH_SEAL_HASH_CONFLICT = "BATCH_SEAL_HASH_CONFLICT"
    BATCH_RECORD_COUNT_MISMATCH = "BATCH_RECORD_COUNT_MISMATCH"
    BATCH_MUTATION_AFTER_SEAL = "BATCH_MUTATION_AFTER_SEAL"
    BATCH_SEAL_CHANGED = "BATCH_SEAL_CHANGED"
    IDENTITY_MAPPING_POLICY_VERSION_MISSING = "IDENTITY_MAPPING_POLICY_VERSION_MISSING"
    IDENTITY_MAPPING_REGISTRY_NOT_SEALED = "IDENTITY_MAPPING_REGISTRY_NOT_SEALED"
    IDENTITY_MAPPING_REGISTRY_HASH_CHANGED = "IDENTITY_MAPPING_REGISTRY_HASH_CHANGED"
    IDENTITY_MAPPING_TARGET_TYPE_UNSUPPORTED = "IDENTITY_MAPPING_TARGET_TYPE_UNSUPPORTED"
    SEASON_RESOLUTION_NOT_FOUND = "SEASON_RESOLUTION_NOT_FOUND"
    SEASON_RESOLUTION_AMBIGUOUS = "SEASON_RESOLUTION_AMBIGUOUS"
    SEASON_BUSINESS_DATE_MISMATCH = "SEASON_BUSINESS_DATE_MISMATCH"
    VALIDATION_IN_PROGRESS = "VALIDATION_IN_PROGRESS"
    VALIDATION_EVIDENCE_STALE = "VALIDATION_EVIDENCE_STALE"
    COMMITTED_LINEAGE_BASIS_CHANGED = "COMMITTED_LINEAGE_BASIS_CHANGED"
    # I7 lineage contract hardening
    # (see q2a-i7-label-snapshot-and-revision-winner-contract.md §9-§10)
    CORRECTED_WITHOUT_SUCCESSOR = "CORRECTED_WITHOUT_SUCCESSOR"
    FINALIZED_HAS_SUCCESSOR = "FINALIZED_HAS_SUCCESSOR"
    VOID_HAS_SUCCESSOR = "VOID_HAS_SUCCESSOR"
    FINALIZED_AT_REQUIRED = "FINALIZED_AT_REQUIRED"
    SOURCE_SYSTEM_SCOPE_CONFLICT = "SOURCE_SYSTEM_SCOPE_CONFLICT"


class SpreadsheetDiagnosticCode(StrEnum):
    CSV_EMPTY_ROW_IGNORED = "CSV_EMPTY_ROW_IGNORED"
    XLSX_EMPTY_ROW_IGNORED = "XLSX_EMPTY_ROW_IGNORED"
