from __future__ import annotations

from enum import StrEnum


class CapacityPoolGrain(StrEnum):
    SUBFARM_VARIETY = "SUBFARM_VARIETY"
    SUBFARM = "SUBFARM"
    FARM = "FARM"


class CapacityInputMode(StrEnum):
    LABOR_DERIVED = "LABOR_DERIVED"
    DIRECT_CAPACITY = "DIRECT_CAPACITY"


class ForecastQuantile(StrEnum):
    P50 = "P50"
    P80 = "P80"
    P90 = "P90"


class Task9AStatus(StrEnum):
    COMPLETED = "completed"
    BLOCKED = "blocked"


class SourceRefType(StrEnum):
    TASK8_DAILY_PREDICTION = "TASK8_DAILY_PREDICTION"
    INITIAL_INVENTORY_SNAPSHOT = "INITIAL_INVENTORY_SNAPSHOT"
    PARAMETER_SOURCE = "PARAMETER_SOURCE"


class WeatherCombinationMethod(StrEnum):
    MULTIPLY = "MULTIPLY"


class ParameterCode(StrEnum):
    DIRECT_NOMINAL_CAPACITY = "DIRECT_NOMINAL_CAPACITY"
    PLANNED_PICKER_COUNT = "PLANNED_PICKER_COUNT"
    PICKER_PRODUCTIVITY = "PICKER_PRODUCTIVITY"
    LABOR_AVAILABILITY_RATIO = "LABOR_AVAILABILITY_RATIO"
    OPERATIONAL_EFFICIENCY_RATIO = "OPERATIONAL_EFFICIENCY_RATIO"
    HOLIDAY_CALENDAR = "HOLIDAY_CALENDAR"
    WEATHER_RULE_CONFIG = "WEATHER_RULE_CONFIG"
    WEATHER_FEATURE_OBSERVATION = "WEATHER_FEATURE_OBSERVATION"
    HARVEST_TO_ARRIVAL_LAG = "HARVEST_TO_ARRIVAL_LAG"
    TIMEZONE_CONFIG = "TIMEZONE_CONFIG"
    HARVEST_BUCKET_ANCHOR_TIME = "HARVEST_BUCKET_ANCHOR_TIME"
    MATURE_INVENTORY_LOSS = "MATURE_INVENTORY_LOSS"


CANONICAL_FORECAST_QUANTILES: tuple[ForecastQuantile, ...] = (
    ForecastQuantile.P50,
    ForecastQuantile.P80,
    ForecastQuantile.P90,
)

OUTPUT_SCHEMA_VERSION = "task9a-output-v1"
SOURCE_REF_SCHEMA_VERSION = "task9a-source-ref-v1"
STABLE_COHORT_KEY_SCHEMA_VERSION = "task9a-cohort-key-v1"
RESOLVED_PARAMETER_SNAPSHOT_SCHEMA_VERSION = "task9a-resolved-parameters-v1"
RESULT_HASH_SCHEMA_VERSION = "task9a-result-hash-v1"


class BlockerCode:
    UNSUPPORTED_CAPACITY_POOL_GRAIN = "UNSUPPORTED_CAPACITY_POOL_GRAIN"
    CROSS_FARM_CAPACITY_POOL = "CROSS_FARM_CAPACITY_POOL"
    INVALID_SINGLETON_POOL = "INVALID_SINGLETON_POOL"
    POOL_MEMBER_GRAIN_MISMATCH = "POOL_MEMBER_GRAIN_MISMATCH"
    DUPLICATE_POOL_MEMBER = "DUPLICATE_POOL_MEMBER"
    MEMBER_ASSIGNED_TO_MULTIPLE_POOLS = "MEMBER_ASSIGNED_TO_MULTIPLE_POOLS"
    MISSING_POOL_MEMBERSHIP = "MISSING_POOL_MEMBERSHIP"
    DUPLICATE_POOL_CAPACITY = "DUPLICATE_POOL_CAPACITY"
    CAPACITY_COPIED_TO_MEMBER_ROWS = "CAPACITY_COPIED_TO_MEMBER_ROWS"
    UNSUPPORTED_SOURCE_REF_TYPE = "UNSUPPORTED_SOURCE_REF_TYPE"
    UNSUPPORTED_SOURCE_REF_SCHEMA_VERSION = "UNSUPPORTED_SOURCE_REF_SCHEMA_VERSION"
    TASK8_SOURCE_RELATION_MISMATCH = "TASK8_SOURCE_RELATION_MISMATCH"
    TASK8_SOURCE_SIGNATURE_MISMATCH = "TASK8_SOURCE_SIGNATURE_MISMATCH"
    TASK8_ARTIFACT_HASH_MISMATCH = "TASK8_ARTIFACT_HASH_MISMATCH"
    TASK8_QUANTILE_VALUE_MISMATCH = "TASK8_QUANTILE_VALUE_MISMATCH"
    TASK8_FORECAST_NOT_COMPLETED = "TASK8_FORECAST_NOT_COMPLETED"
    INITIAL_SOURCE_NOT_VISIBLE_AT_AS_OF = "INITIAL_SOURCE_NOT_VISIBLE_AT_AS_OF"
    INITIAL_SOURCE_ROW_HASH_MISSING = "INITIAL_SOURCE_ROW_HASH_MISSING"
    STABLE_COHORT_KEY_MISMATCH = "STABLE_COHORT_KEY_MISMATCH"
    DUPLICATE_STABLE_COHORT_KEY = "DUPLICATE_STABLE_COHORT_KEY"
    COHORT_IDENTITY_COLLISION = "COHORT_IDENTITY_COLLISION"
    COHORT_KEY_CHANGED_ACROSS_DAYS = "COHORT_KEY_CHANGED_ACROSS_DAYS"
    DUPLICATE_MATURE_LOSS_INPUT = "DUPLICATE_MATURE_LOSS_INPUT"
    MATURE_LOSS_COPIED_TO_MEMBER_ROWS = "MATURE_LOSS_COPIED_TO_MEMBER_ROWS"
    MISSING_RESOLVED_PARAMETER = "MISSING_RESOLVED_PARAMETER"
    CAPACITY_MODE_FIELD_CONFLICT = "CAPACITY_MODE_FIELD_CONFLICT"
    CAPACITY_MODE_PROVENANCE_MISSING = "CAPACITY_MODE_PROVENANCE_MISSING"
    PARAMETER_SOURCE_NOT_VISIBLE_AT_AS_OF = "PARAMETER_SOURCE_NOT_VISIBLE_AT_AS_OF"
    UNKNOWN_PARAMETER_CODE = "UNKNOWN_PARAMETER_CODE"
    PARAMETER_SOURCE_CONFLICT = "PARAMETER_SOURCE_CONFLICT"
    POOL_MEMBER_SUM_MISMATCH = "POOL_MEMBER_SUM_MISMATCH"
    POOL_COHORT_SUM_MISMATCH = "POOL_COHORT_SUM_MISMATCH"
    COHORT_TRANSITION_EQUATION_FAILED = "COHORT_TRANSITION_EQUATION_FAILED"
    SOURCE_REF_HASH_MISMATCH = "SOURCE_REF_HASH_MISMATCH"
    SOURCE_REF_HASH_COLLISION = "SOURCE_REF_HASH_COLLISION"
    UNRESOLVED_SOURCE_REF = "UNRESOLVED_SOURCE_REF"
    ORPHAN_SOURCE_REF = "ORPHAN_SOURCE_REF"
    DUPLICATE_DAILY_POOL_STATE_KEY = "DUPLICATE_DAILY_POOL_STATE_KEY"
    DUPLICATE_DAILY_MEMBER_STATE_KEY = "DUPLICATE_DAILY_MEMBER_STATE_KEY"
    DUPLICATE_COHORT_TRANSITION_KEY = "DUPLICATE_COHORT_TRANSITION_KEY"
    MISSING_INITIAL_INVENTORY_COHORTS = "MISSING_INITIAL_INVENTORY_COHORTS"
    INITIAL_INVENTORY_SUM_MISMATCH = "INITIAL_INVENTORY_SUM_MISMATCH"
    MISSING_WEATHER_FEATURE = "MISSING_WEATHER_FEATURE"
    WEATHER_RULE_BAND_OVERLAP = "WEATHER_RULE_BAND_OVERLAP"
    WEATHER_RULE_BAND_GAP = "WEATHER_RULE_BAND_GAP"
    MISSING_MATURE_LOSS_INPUT = "MISSING_MATURE_LOSS_INPUT"
    MATURE_LOSS_EXCEEDS_AVAILABLE = "MATURE_LOSS_EXCEEDS_AVAILABLE"
    MISSING_HARVEST_BUCKET_ANCHOR_TIME = "MISSING_HARVEST_BUCKET_ANCHOR_TIME"
    INVALID_TIMEZONE = "INVALID_TIMEZONE"
    INVALID_ARRIVAL_LAG = "INVALID_ARRIVAL_LAG"
    NATIVE_FLOAT_INPUT = "NATIVE_FLOAT_INPUT"
